name: Manual compact build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Cache restore
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: src/main/generated
        key: datagen-${{ github.run_id }}
        restore-keys:
          datagen-
    
    - name: Build
      run: |
        ./gradlew --configuration-cache runDatagen
        ./gradlew --configuration-cache build

    - name: Run PackSquash
      uses: drtheodor/PackSquash-action@9df4689ee0fdb105de4d16ee9fb319fbbd81ec28
      with:
        packsquash_version: latest
        quiet_logs: true
        options: |
          pack_directory = './build/resources/main/'
          output_file_path = '/tmp/pack.zip'

    - name: Combine
      run: ./scripts/merge_jar ./build/libs/ /tmp/pack.zip
    
    - uses: actions/upload-artifact@v4
      with:
        name: Build
        path: build/libs/*.jar
    
    - name: Cache save
      id: cache-save
      uses: actions/cache/save@v4
      with:
        path: src/main/generated
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}
