name: Generate Changelog
on:
  workflow_dispatch:
  push:
    branches:
      - release
      - release/*
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r scripts/requirements.txt
      - run: python scripts/generate_changelogs.py
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Generate changelog
