name: "Labels: Approve"
on:
  pull_request_review:
    types: [submitted]
jobs:
  add_labels:
    # Change the repository name after you've made sure the team name is correct for your fork!
    if: ${{ github.repository == 'amblelabs/ait' }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: tspascoal/get-user-teams-membership@v3
        id: checkUserMember
        with:
          username: ${{ github.actor }}
          team: "development"
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
      - if: ${{ steps.checkUserMember.outputs.isTeamMember == 'true' && github.event.review.state == 'APPROVED' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "S: Approved"
      - if: ${{ steps.checkUserMember.outputs.isTeamMember == 'true' && github.event.review.state == 'APPROVED' }}
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "S: Needs Review"
      
      - if: ${{ steps.checkUserMember.outputs.isTeamMember == 'true' && github.event.review.state != 'APPROVED' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "S: Awaiting Changes"
      - if: ${{ steps.checkUserMember.outputs.isTeamMember == 'true' && github.event.review.state != 'APPROVED' }}
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "S: Needs Review"