name: Publish on GitHub, Modrinth, and CurseForge

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Generate Changelog
    types:
      - completed

env:
  JAVA_VERSION: 17

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # For PackSquash

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 21
          cache: gradle

      - name: Build
        run: |
          ./gradlew runDatagen
          ./gradlew build

      - name: Run PackSquash
        uses: drtheodor/PackSquash-action@9df4689ee0fdb105de4d16ee9fb319fbbd81ec28
        with:
          packsquash_version: latest
          quiet_logs: true
          options: |
            pack_directory = './build/resources/main/'
            output_file_path = '/tmp/pack.zip'

      - name: Combine
        run: ./scripts/merge_jar ./build/libs/ /tmp/pack.zip
    
      - name: Publish (CurseForge/Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3.3                                   #The specified MC-Publish GitHub Action in the version 3.2
        with:
          changelog-file: CHANGELOG.md
          curseforge-id: 856138                                             #The id of your CurseForge project
          curseforge-token: "${{secrets.CURSEFORGE_TOKEN}}"

          modrinth-id: ZMP9ZjB9                                             #The id of your modrinth project
          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"

          github-token: "${{secrets.GITHUB_TOKEN}}"

          github-generate-changelog: true
          version-type: release

          loaders: fabric
          java: "${{env.JAVA_VERSION}}"
